In [65]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
pd.set_option("display.max_columns", None)

df = pd.read_csv(r'C:\Users\Денис\Documents\Программирование\Python\EDA\imports-85 (1).data')

print(df)

     3    ?  alfa-romero     gas    std   two  convertible  rwd  front  88.60  \
0    3    ?  alfa-romero     gas    std   two  convertible  rwd  front   88.6
1    1    ?  alfa-romero     gas    std   two    hatchback  rwd  front   94.5
2    2  164         audi     gas    std  four        sedan  fwd  front   99.8
3    2  164         audi     gas    std  four        sedan  4wd  front   99.4
4    2    ?         audi     gas    std   two        sedan  fwd  front   99.8
..  ..  ...          ...     ...    ...   ...          ...  ...    ...    ...
199 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
200 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1
201 -1   95        volvo     gas    std  four        sedan  rwd  front  109.1
202 -1   95        volvo  diesel  turbo  four        sedan  rwd  front  109.1
203 -1   95        volvo     gas  turbo  four        sedan  rwd  front  109.1

     168.80  64.10  48.80  2548  dohc  four  130  mpfi  3.47  2.68  9.00  111  \
0     168.8   64.1   48.8  2548  dohc  four  130  mpfi  3.47  2.68   9.0  111
1     171.2   65.5   52.4  2823  ohcv   six  152  mpfi  2.68  3.47   9.0  154
2     176.6   66.2   54.3  2337   ohc  four  109  mpfi  3.19  3.40  10.0  102
3     176.6   66.4   54.3  2824   ohc  five  136  mpfi  3.19  3.40   8.0  115
4     177.3   66.3   53.1  2507   ohc  five  136  mpfi  3.19  3.40   8.5  110
..      ...    ...    ...   ...   ...   ...  ...   ...   ...   ...   ...  ...
199   188.8   68.9   55.5  2952   ohc  four  141  mpfi  3.78  3.15   9.5  114
200   188.8   68.8   55.5  3049   ohc  four  141  mpfi  3.78  3.15   8.7  160
201   188.8   68.9   55.5  3012  ohcv   six  173  mpfi  3.58  2.87   8.8  134
202   188.8   68.9   55.5  3217   ohc   six  145   idi  3.01  3.40  23.0  106
203   188.8   68.9   55.5  3062   ohc  four  141  mpfi  3.78  3.15   9.5  114

     5000  21  27  13495
0    5000  21  27  16500
1    5000  19  26  16500
2    5500  24  30  13950
3    5500  18  22  17450
4    5500  19  25  15250
..    ...  ..  ..    ...
199  5400  23  28  16845
200  5300  19  25  19045
201  5500  18  23  21485
202  4800  26  27  22470
203  5400  19  25  22625

[204 rows x 26 columns]

При чтении файла первая строка данных была ошибочно принята за заголовки колонок. Поскольку в файле нет заголовков, добавлен параметр header = None.

In [66]:
df = pd.read_csv(r"C:\Users\Денис\Documents\Программирование\Python\EDA\imports-85 (1).data", header=None)

In [67]:
df.head(30)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.00,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.00,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.00,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.00,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.40,8.50,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.40,8.50,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.40,8.50,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.30,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0,3053,ohc,five,131,mpfi,3.13,3.40,7.00,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.50,2.80,8.80,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2710,ohc,six,164,mpfi,3.31,3.19,9.00,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2765,ohc,six,164,mpfi,3.31,3.19,9.00,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3055,ohc,six,164,mpfi,3.31,3.19,9.00,121,4250,20,25,24565
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7,3230,ohc,six,209,mpfi,3.62,3.39,8.00,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,six,209,mpfi,3.62,3.39,8.00,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,197.0,70.9,56.3,3505,ohc,six,209,mpfi,3.62,3.39,8.00,182,5400,15,20,36880
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,53.2,1488,l,three,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,155.9,63.6,52.0,1874,ohc,four,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,158.8,63.6,52.0,1909,ohc,four,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6575
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,1876,ohc,four,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,1876,ohc,four,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377
23,1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,2128,ohc,four,98,mpfi,3.03,3.39,7.60,102,5500,24,30,7957
24,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,157.3,63.8,50.6,1967,ohc,four,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6229
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,50.6,1989,ohc,four,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6692
26,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,50.6,1989,ohc,four,90,2bbl,2.97,3.23,9.40,68,5500,31,38,7609
27,1,148,dodge,gas,turbo,?,sedan,fwd,front,93.7,157.3,63.8,50.6,2191,ohc,four,98,mpfi,3.03,3.39,7.60,102,5500,24,30,8558
28,-1,110,dodge,gas,std,four,wagon,fwd,front,103.3,174.6,64.6,59.8,2535,ohc,four,122,2bbl,3.34,3.46,8.50,88,5000,24,30,8921
29,3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,2811,ohc,four,156,mfi,3.60,3.90,7.00,145,5000,19,24,12964

Продолжаю работу с названием заголовков. Даю им названия, которые соответсвуют названиям из документации.

In [68]:
column_names = [
    "Symboling", "Normalized-losses", "Make", "Fuel-type",
    "Aspiration", "Num-of-doors", "Body-style", "Drive-wheels",
    "Engine-location", "Wheel-base", "Length", "Width", "Height",
    "Curb-weight", "Engine-type", "Num-of-cylinders", "Engine-size",
    "Fuel-system", "Bore", "Stroke", "Compression-ratio",
    "Horsepower", "Peak-rpm", "City-mpg", "Highway-mpg", "Price"
]

df.columns = column_names

df.head()

,Symboling,Normalized-losses,Make,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,Length,Width,Height,Curb-weight,Engine-type,Num-of-cylinders,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [69]:
df.shape

(205, 26)

У нас есть 205 строк и 26 колонок. Таблица относительно не большого размера.

In [70]:
df.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Symboling          205 non-null    int64
 1   Normalized-losses  205 non-null    str
 2   Make               205 non-null    str
 3   Fuel-type          205 non-null    str
 4   Aspiration         205 non-null    str
 5   Num-of-doors       205 non-null    str
 6   Body-style         205 non-null    str
 7   Drive-wheels       205 non-null    str
 8   Engine-location    205 non-null    str
 9   Wheel-base         205 non-null    float64
 10  Length             205 non-null    float64
 11  Width              205 non-null    float64
 12  Height             205 non-null    float64
 13  Curb-weight        205 non-null    int64
 14  Engine-type        205 non-null    str
 15  Num-of-cylinders   205 non-null    str
 16  Engine-size        205 non-null    int64
 17  Fuel-system        205 non-null    str
 18  Bore               205 non-null    str
 19  Stroke             205 non-null    str
 20  Compression-ratio  205 non-null    float64
 21  Horsepower         205 non-null    str
 22  Peak-rpm           205 non-null    str
 23  City-mpg           205 non-null    int64
 24  Highway-mpg        205 non-null    int64
 25  Price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 54.4 KB

Пропуски не имеются.

In [71]:
df.dtypes

Symboling              int64
Normalized-losses        str
Make                     str
Fuel-type                str
Aspiration               str
Num-of-doors             str
Body-style               str
Drive-wheels             str
Engine-location          str
Wheel-base           float64
Length               float64
Width                float64
Height               float64
Curb-weight            int64
Engine-type              str
Num-of-cylinders         str
Engine-size            int64
Fuel-system              str
Bore                     str
Stroke                   str
Compression-ratio    float64
Horsepower               str
Peak-rpm                 str
City-mpg               int64
Highway-mpg            int64
Price                    str
dtype: object

В таблице есть числовые и текстовые признаки. Некоторые количественные характеристики, включая цену и мощность, прочитаны как строки. Требуется выяснить причину и проверить возможность преобразования в числовой тип.

In [72]:
df['Engine-location']

0      front
1      front
2      front
3      front
4      front
       ...
200    front
201    front
202    front
203    front
204    front
Name: Engine-location, Length: 205, dtype: str

Num-of-doors (кол-во дверей) записано текстом, а не числами.

In [73]:
df["Num-of-doors"] = df["Num-of-doors"].map({"two": 2, "four": 4})

In [74]:
df['Price']

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: Price, Length: 205, dtype: str

In [75]:
df['Num-of-cylinders']

0      four
1      four
2       six
3      four
4      five
       ...
200    four
201    four
202     six
203     six
204    four
Name: Num-of-cylinders, Length: 205, dtype: str

In [76]:
df["Num-of-cylinders"].unique()

<ArrowStringArray>
['four', 'six', 'five', 'three', 'twelve', 'two', 'eight']
Length: 7, dtype: str

In [77]:
df['Num-of-cylinders'] = df['Num-of-cylinders'].map({'four': 4, 
                                                    'six': 6,
                                                    'five': 5,
                                                    'three': 3,
                                                    'twelve': 12,
                                                    'two': 2,
                                                    'eight': 8})

In [78]:
df['Num-of-cylinders']

0      4
1      4
2      6
3      4
4      5
      ..
200    4
201    4
202    6
203    6
204    4
Name: Num-of-cylinders, Length: 205, dtype: int64

In [79]:
df['Price']

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: Price, Length: 205, dtype: str

In [80]:
df = df.replace('?', pd.NA)

In [81]:
df["Price"] = pd.to_numeric(df["Price"])

In [82]:
df.dtypes

Symboling              int64
Normalized-losses        str
Make                     str
Fuel-type                str
Aspiration               str
Num-of-doors         float64
Body-style               str
Drive-wheels             str
Engine-location          str
Wheel-base           float64
Length               float64
Width                float64
Height               float64
Curb-weight            int64
Engine-type              str
Num-of-cylinders       int64
Engine-size            int64
Fuel-system              str
Bore                     str
Stroke                   str
Compression-ratio    float64
Horsepower               str
Peak-rpm                 str
City-mpg               int64
Highway-mpg            int64
Price                float64
dtype: object

In [83]:
df[['Normalized-losses', 
    'Fuel-type', 
    'Aspiration', 
    'Body-style', 
    'Drive-wheels', 
    'Engine-location', 
    'Engine-type',
    'Fuel-system',
    'Bore',
    'Stroke',
    'Horsepower',
    'Peak-rpm',
    
]].head(30)

,Normalized-losses,Fuel-type,Aspiration,Body-style,Drive-wheels,Engine-location,Engine-type,Fuel-system,Bore,Stroke,Horsepower,Peak-rpm
0,NaN,gas,std,convertible,rwd,front,dohc,mpfi,3.47,2.68,111,5000
1,NaN,gas,std,convertible,rwd,front,dohc,mpfi,3.47,2.68,111,5000
2,NaN,gas,std,hatchback,rwd,front,ohcv,mpfi,2.68,3.47,154,5000
3,164,gas,std,sedan,fwd,front,ohc,mpfi,3.19,3.40,102,5500
4,164,gas,std,sedan,4wd,front,ohc,mpfi,3.19,3.40,115,5500
5,NaN,gas,std,sedan,fwd,front,ohc,mpfi,3.19,3.40,110,5500
6,158,gas,std,sedan,fwd,front,ohc,mpfi,3.19,3.40,110,5500
7,NaN,gas,std,wagon,fwd,front,ohc,mpfi,3.19,3.40,110,5500
8,158,gas,turbo,sedan,fwd,front,ohc,mpfi,3.13,3.40,140,5500
9,NaN,gas,turbo,hatchback,4wd,front,ohc,mpfi,3.13,3.40,160,5500
10,192,gas,std,sedan,rwd,front,ohc,mpfi,3.50,2.80,101,5800
11,192,gas,std,sedan,rwd,front,ohc,mpfi,3.50,2.80,101,5800
12,188,gas,std,sedan,rwd,front,ohc,mpfi,3.31,3.19,121,4250
13,188,gas,std,sedan,rwd,front,ohc,mpfi,3.31,3.19,121,4250
14,NaN,gas,std,sedan,rwd,front,ohc,mpfi,3.31,3.19,121,4250
15,NaN,gas,std,sedan,rwd,front,ohc,mpfi,3.62,3.39,182,5400
16,NaN,gas,std,sedan,rwd,front,ohc,mpfi,3.62,3.39,182,5400
17,NaN,gas,std,sedan,rwd,front,ohc,mpfi,3.62,3.39,182,5400
18,121,gas,std,hatchback,fwd,front,l,2bbl,2.91,3.03,48,5100
19,98,gas,std,hatchback,fwd,front,ohc,2bbl,3.03,3.11,70,5400
20,81,gas,std,sedan,fwd,front,ohc,2bbl,3.03,3.11,70,5400
21,118,gas,std,hatchback,fwd,front,ohc,2bbl,2.97,3.23,68,5500
22,118,gas,std,hatchback,fwd,front,ohc,2bbl,2.97,3.23,68,5500
23,118,gas,turbo,hatchback,fwd,front,ohc,mpfi,3.03,3.39,102,5500
24,148,gas,std,hatchback,fwd,front,ohc,2bbl,2.97,3.23,68,5500
25,148,gas,std,sedan,fwd,front,ohc,2bbl,2.97,3.23,68,5500
26,148,gas,std,sedan,fwd,front,ohc,2bbl,2.97,3.23,68,5500
27,148,gas,turbo,sedan,fwd,front,ohc,mpfi,3.03,3.39,102,5500
28,110,gas,std,wagon,fwd,front,ohc,2bbl,3.34,3.46,88,5000
29,145,gas,turbo,hatchback,fwd,front,ohc,mfi,3.60,3.90,145,5000

In [84]:
df.isna().sum()

Symboling             0
Normalized-losses    41
Make                  0
Fuel-type             0
Aspiration            0
Num-of-doors          2
Body-style            0
Drive-wheels          0
Engine-location       0
Wheel-base            0
Length                0
Width                 0
Height                0
Curb-weight           0
Engine-type           0
Num-of-cylinders      0
Engine-size           0
Fuel-system           0
Bore                  4
Stroke                4
Compression-ratio     0
Horsepower            2
Peak-rpm              2
City-mpg              0
Highway-mpg           0
Price                 4
dtype: int64

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Symboling          205 non-null    int64
 1   Normalized-losses  164 non-null    str
 2   Make               205 non-null    str
 3   Fuel-type          205 non-null    str
 4   Aspiration         205 non-null    str
 5   Num-of-doors       203 non-null    float64
 6   Body-style         205 non-null    str
 7   Drive-wheels       205 non-null    str
 8   Engine-location    205 non-null    str
 9   Wheel-base         205 non-null    float64
 10  Length             205 non-null    float64
 11  Width              205 non-null    float64
 12  Height             205 non-null    float64
 13  Curb-weight        205 non-null    int64
 14  Engine-type        205 non-null    str
 15  Num-of-cylinders   205 non-null    int64
 16  Engine-size        205 non-null    int64
 17  Fuel-system        205 non-null    str
 18  Bore               201 non-null    str
 19  Stroke             201 non-null    str
 20  Compression-ratio  205 non-null    float64
 21  Horsepower         203 non-null    str
 22  Peak-rpm           203 non-null    str
 23  City-mpg           205 non-null    int64
 24  Highway-mpg        205 non-null    int64
 25  Price              201 non-null    float64
dtypes: float64(7), int64(6), str(13)
memory usage: 52.1 KB